# Generated by Django 4.2.1 on 2023-05-31 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_player2_remove_player_skill_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='player2',
            new_name='member',
        ),
    ]
