# Generated by Django 4.2.1 on 2023-06-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_player_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Wednesday', 'Wednesday')], max_length=10),
        ),
    ]
