# Generated by Django 4.2.1 on 2023-06-14 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_player_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='member',
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
